name: Add or Update AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: "Name of the secret in AWS Secrets Manager"
        required: true
        type: string
      secret-key:
        description: "Key inside the JSON secret"
        required: true
        type: string
      secret-value:
        description: "Value for the key"
        required: true
        type: string

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: "1.6"
          force: true

      - name: Fetch current secret (if exists)
        id: get-secret
        continue-on-error: true
        run: |
          echo "Fetching existing secret..."
          SECRET_VALUE=$(aws secretsmanager get-secret-value \
            --secret-id "${{ github.event.inputs.secret-name }}" \
            --query SecretString \
            --output text 2>/dev/null || echo "{}")

          echo "secret_json=$SECRET_VALUE" >> $GITHUB_OUTPUT

      - name: Merge new key/value and update secret
        run: |
          CURRENT_SECRET='${{ steps.get-secret.outputs.secret_json }}'
          NEW_PAIR="{\"${{ github.event.inputs.secret-key }}\":\"${{ github.event.inputs.secret-value }}\"}"

          echo "Merging existing secret with new key/value..."
          MERGED_SECRET=$(jq -s '.[0] * .[1]' <(echo "$CURRENT_SECRET") <(echo "$NEW_PAIR"))

          echo "Updating secret in AWS Secrets Manager..."
          aws secretsmanager put-secret-value \
            --secret-id "${{ github.event.inputs.secret-name }}" \
            --secret-string "$MERGED_SECRET"

