name: Add or Update a Key/Value Pair in AWS Secrets

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Secret Key Name'
        type: string
        required: true
      value:
        description: 'Secret Key Value'
        type: string
        required: true

env:
  PRODUCTION_SECRET_KEY: Main-secret  # Secret name for production

jobs:
  aws-secrets-production:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
  
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.8'
          force: true
  
      - name: Load Production Secret
        id: get-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: AWS_SECRET,${{ env.PRODUCTION_SECRET_KEY }}
  
      - name: Process and Update Key-Value Pair
        shell: bash
        run: |
          jq --version
          echo "INFO: Working with production environment."
          
          # Initialize the new JSON object
          MERGED_SECRET="$AWS_SECRET"
          
          # Check and process the key-value pair
          if [[ "${{ inputs.key }}" != "" ]] && [[ "${{ inputs.value }}" != "" ]]; then
            NEW_JSON_OBJ="{ \"${{ inputs.key }}\": \"${{ inputs.value }}\"}"
            MERGED_SECRET=$(echo "$MERGED_SECRET" | jq -s '.[0] * .[1]' <(echo "$MERGED_SECRET") <(echo "$NEW_JSON_OBJ"))
          fi

          # Update the secret in AWS Secrets Manager
          echo "INFO: Updating Production Secret"
          aws secretsmanager put-secret-value \
            --secret-id "${SECRET_KEY}" \
            --secret-string "${MERGED_SECRET}"
        env:
          SECRET_KEY: ${{ env.PRODUCTION_SECRET_KEY }}
