name: Deploy ECS Infrastructure
'on':
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:

  deploy-prod:
    name: Deploy ECS + LB Prod via Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.13.3

      - name: Create or Update ECS Service
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/prod
          auto_approve: true
          backend_config: key=infrastructure-main.tfstate
